# Generated by Django 5.2.6 on 2025-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_for_author',
            field=models.BooleanField(default=False),
        ),
    ]
