# Generated by Django 5.2.6 on 2026-06-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_reviewaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationanalysis',
            name='application',
        ),
        migrations.RemoveField(
            model_name='reviewaction',
            name='application',
        ),
        migrations.RemoveField(
            model_name='reviewaction',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='application',
        ),
        migrations.RemoveField(
            model_name='writerapplication',
            name='preview_blog',
        ),
        migrations.RemoveField(
            model_name='writerapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='AgentDecision',
        ),
        migrations.DeleteModel(
            name='ApplicationAnalysis',
        ),
        migrations.DeleteModel(
            name='ReviewAction',
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
        migrations.DeleteModel(
            name='WriterApplication',
        ),
    ]
