# Generated by Django 5.2.6 on 2026-06-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_applicationanalysis_application_and_more'),
        ('review_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerapplication',
            name='submitted_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writerapplication',
            name='submitted_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='writerapplication',
            name='preview_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.post'),
        ),
    ]
