# Generated by Django 5.2.6 on 2026-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_center', '0002_writerapplication_submitted_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationanalysis',
            name='overall_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='ai_generated_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writerapplication',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
