# Generated by Django 5.2.6 on 2026-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_center', '0003_applicationanalysis_overall_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationanalysis',
            name='strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationanalysis',
            name='weaknesses',
            field=models.TextField(blank=True, default=''),
        ),
    ]
