# Generated by Django 5.2.6 on 2026-08-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_center', '0004_applicationanalysis_strengths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='applicationanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
