# Generated by Django 5.2.6 on 2026-08-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_center', '0006_alter_applicationanalysis_strengths_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='explanation',
            new_name='overall_explanation',
        ),
        migrations.AlterField(
            model_name='agentdecision',
            name='confidence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationanalysis',
            name='grammar_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationanalysis',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicationanalysis',
            name='readability_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationanalysis',
            name='structure_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationanalysis',
            name='writing_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_score',
            field=models.IntegerField(),
        ),
    ]
