# Generated by Django 5.2.6 on 2026-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_center', '0007_rename_explanation_riskassessment_overall_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerapplication',
            name='auto_confirmation_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='writerapplication',
            name='confirmation_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
